#!/usr/bin/python


import json
from collections import Counter


def get_count(sequence):
    counts = {}
    for x in sequence:
        if x in counts:
            counts[x] += 1
        else:
            counts[x] = 1
    return counts


def top_counts(count_dict, n=10):
    value_key_pairs = [(count, tz) for tz, count in count_dict.items()]
    value_key_pairs.sort()
    return value_key_pairs[-n:]


if __name__ == '__main__':
    path = '/home/hiro/Documents/pydata-book/ch02/usagov_bitly_data2012-03-16-1331923249.txt'

    records = [json.loads(line) for line in open(path)]

    timezones = [rec['tz'] for rec in records if 'tz' in rec]
    # counts = get_count(timezones)

    counts = Counter(timezones)
    print(counts.most_common(10))
